on:
  push:
  workflow_dispatch:

jobs:
  build_and_maybe_deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-1
      AWS_ECR_URI: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.AWS_ECR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build image
        run: |
          rev=$(git rev-parse --short HEAD)
          docker build . -t $AWS_ECR_URI:$rev
      - name: Deploy to aws ECR
        if: github.ref_name == 'main'
        run: |
          aws ecr get-login-password | docker login -u AWS --password-stdin $AWS_ECR_URI
          rev=$(git rev-parse --short HEAD)
          docker tag $AWS_ECR_URI:$rev $AWS_ECR_URI:latest
          docker push $AWS_ECR_URI:$rev
          docker push $AWS_ECR_URI:latest

  infrastructure:
    runs-on: ubuntu-latest
    needs: build_and_maybe_deploy
    defaults:
      run:
        working-directory: ./infra
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      TF_VAR_service_name: ${{ vars.SERVICE_NAME }}
      TF_VAR_aws_account_number: ${{ vars.AWS_ACCOUNT_ID }}
      TF_VAR_cloudwatch_namespace: ${{ vars.CLOUDWATCH_NAMESPACE }}
      TF_VAR_aws_region: ${{ vars.AWS_REGION }}
      TF_VAR_ecr_repository: ${{ vars.AWS_ECR }}
      # TF_VAR_ecr_tag: ${{ vars.AWS_ECR_TAG }} # Optional, defaults to latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
      - name: Init
        run: terraform init
      - name: Validate
        run: terraform validate -no-color
      - name: Plan
        run: terraform plan -no-color -out plan
      - name: Apply
        if: github.ref_name == 'main' # Only apply if on main
        run: terraform apply -auto-approve ./plan